---

- hosts: "all"
  become: True
  gather_facts: false

  vars:
    acme_sh_become_user: "test"

  vars_files:
    - 'defaults/main.yml'  

  tasks:
    - include: 'tasks/main.yml'  

  post_tasks:
    - name: Ensure acme.sh was cloned
      command: test -d /usr/local/src/acme.sh
      register: result_cloned
      changed_when: result_cloned.rc != 0

    - name: Ensure acme.sh was installed
      command: ./acme.sh --version
      args:
        chdir: "~/.acme.sh"
      register: result_installed
      changed_when: result_installed.rc != 0

    - name: Ensure certificate installation path exists
      command: test -d /etc/ssl/ansible
      register: result_cert_installed_path
      changed_when: result_cert_installed_path.rc != 0
